using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.InputSystem;
using UnityEngine.Windows;

public class ArrowSystem : MonoBehaviour
{
    public enum ArrowKey { Left, Right, Down, Up, Space };

    public int spawnArrow;
    public GameObject playerHand;
    public GameObject arrowPrefab;
    public Transform arrowParent;

    public EnemyAttackController enemyAttackController;
    public GameObject throwBackGround;
    public Image enemySprite;
    public Animator explosiveAnim;
    public Animator enemyDieEffect;

    public GameObject customer;
    public GameObject waitingcustomer;
    public GameObject waitingCustomer2;
    public GameObject createBread;
    public GameObject arrowBackground;

    public bool isReverse;

    public bool isBombReady;
    private float bombCooldown = 10f;
    public float leftBombCooldown = 0f;

    public float spacing = 100f;
    public float limitTime = 5f;
    public Slider arrowTimer;
    private float currentTime = 0f;
    private List<ArrowKey> sequence = new();
    private int currentKey = 0;
    private bool isActive = false;
    private Queue<int> customerQueue = new Queue<int>();
    private List<int> customerIndexList = new List<int>();

    private Animator animator;
    public Animator Anim => animator;

    private SpriteRenderer sr;

    private void Awake()
    {
        animator = playerHand.GetComponent<Animator>();
        sr = playerHand.GetComponent<SpriteRenderer>();
        throwBackGround.SetActive(false);
    }

    private void Start()
    {
        arrowTimer.gameObject.SetActive(false);
        arrowTimer.maxValue = limitTime;

        for (int i = 0; i < 3; i++)
        {
            customerIndexList.Add(ChangeCustomerSprite());
        }
    }

    private void Update()
    {
        if (isActive)
        {
            if (enemyAttackController.isParrying) return;

            currentTime -= Time.deltaTime;
            arrowTimer.value = currentTime;
            if (currentTime <= 0)
            {
                FailInput();
            }
        }

        if (GameManager.Instance.stageStart && !isBombReady)
        {
            leftBombCooldown -= Time.deltaTime;
            if (leftBombCooldown <= 0 && !isActive)
            {
                isBombReady = true;
            }
        }
    }

    private ArrowKey GetOpposite(ArrowKey key)
    {
        return key switch
        {
            ArrowKey.Left => ArrowKey.Right,
            ArrowKey.Right => ArrowKey.Left,
            ArrowKey.Up => ArrowKey.Down,
            ArrowKey.Down => ArrowKey.Up,
            _ => key // SpaceлҠ” л°ҳлҢҖ м—ҶмқҢ
        };
    }

    /// <summary>
    /// нҷ”мӮҙн‘ң мғқм„ұ л°Ҹ мһ…л Ҙ мӢңнҖёмҠӨлҘј мӢңмһ‘н•©лӢҲлӢӨ
    /// </summary>
    /// <param name="count">мғқм„ұн•  нҷ”мӮҙн‘ңмқҳ к°ңмҲҳ</param>
    public void StartArrowInput()
    {
        customer.SetActive(true);
        waitingcustomer.SetActive(true);
        waitingCustomer2.SetActive(true);

        if (!enemyAttackController.isParrying)
        {
            arrowBackground.SetActive(true);
            arrowTimer.gameObject.SetActive(true);
        }

        arrowBackground.GetComponent<Image>().color = Color.white;
        int nowStage = GameManager.Instance.nowStage;
        int count = 0;
        ClearArrow();

        animator.enabled = true; // лҢҖкё° м• лӢҲл©”мқҙм…ҳ нҷңм„ұнҷ”

        if (nowStage < 3)
        {
            isReverse = false;
        }
        else
        {
            isReverse = Random.value < 0.3f;
        }

        if (nowStage == 1)
        {
            count = 6;
        }
        else if (nowStage == 2)
        {
            count = 7;
        }
        else if (nowStage == 3)
        {
            if (isReverse)
            {
                count = 5;
            }
            else
            {
                count = 8;
            }
        }
        currentTime = limitTime;

        // м •л°©н–Ҙ + мҠӨнҺҳмқҙмҠӨ
        if (!isReverse && nowStage >= 2)
        {
            for (int i = 0; i < count; i++)
            {
                sequence.Add((ArrowKey)Random.Range(0, 5));
                GameObject arrow = Instantiate(arrowPrefab, arrowParent);
                arrow.name = i.ToString();
                Transform child = arrow.transform.Find("Arrow");
                CreateArrow(sequence[i], child);
            }
        }
        // м •л°©н–Ҙ
        else if (!isReverse && nowStage == 1)
        {
            for (int i = 0; i < count; i++)
            {
                Debug.Log("м •л°©н–Ҙ");
                sequence.Add((ArrowKey)Random.Range(0, 4));
                GameObject arrow = Instantiate(arrowPrefab, arrowParent);
                arrow.name = i.ToString();
                Transform child = arrow.transform.Find("Arrow");
                CreateArrow(sequence[i], child);
            }
        }
        // м—ӯл°©н–Ҙ
        else if (isReverse && nowStage >= 3)
        {
            for (int i = 0; i < count; i++)
            {
                sequence.Add((ArrowKey)Random.Range(0, 4));
                arrowBackground.GetComponent<Image>().color = new Color(1f, 0f, 1f);
                GameObject arrow = Instantiate(arrowPrefab, arrowParent);
                arrow.name = i.ToString();
                Transform child = arrow.transform.Find("Arrow");
                CreateArrow(sequence[i], child);
            }
        }

        ArrangeChildrenCentered();
        ClearCustomer();
        GetCustomer();
        currentKey = 0;
        isActive = true;
    }

    // TODO : м¶”нӣ„ (0,7)лЎң мҲҳм •н•  кІғ
    public int ChangeCustomerSprite()
    {
        return Random.Range(0, 6);
    }

    /// <summary>
    /// мғқм„ұлҗң нҷ”мӮҙн‘ңмқҳ keyм—җ л§һкІҢ Resources нҸҙлҚ”м—җм„ң нҷ”мӮҙн‘ң spriteлҘј к°Җм ёмҳҙ
    /// </summary>
    /// <param name="key">лҰ¬мҶҢмҠӨлҘј л¶Ҳлҹ¬мҳ¬ нҷ”мӮҙн‘ң enum</param>
    /// <returns>мһ…л Ҙл°ӣмқҖ нӮӨм—җ л§һлҠ” Sprite</returns>
    private void CreateArrow(ArrowKey key, Transform child)
    {
        string path = $"Arrows/{key}Arrow";
        Sprite arrowSprite = Resources.Load<Sprite>(path);

        child.GetComponent<Image>().sprite = arrowSprite;

        if (key == ArrowKey.Left)
        {
            child.GetComponent<Image>().color = Color.red;
        }
        else if (key == ArrowKey.Right)
        {
            child.GetComponent<Image>().color = Color.green;
        }
        else if (key == ArrowKey.Up)
        {
            child.GetComponent<Image>().color = Color.blue;
        }
        else if (key == ArrowKey.Down)
        {
            child.GetComponent<Image>().color = Color.yellow;
        }
    }

    private void GetCustomer()
    {
        customer.transform.GetChild(customerIndexList[0]).gameObject.SetActive(true);
        waitingcustomer.transform.GetChild(customerIndexList[1]).gameObject.SetActive(true);
        waitingCustomer2.transform.GetChild(customerIndexList[2]).gameObject.SetActive(true);
    }

    private Sprite GetMixHandSprite(string index)
    {
        if (isBombReady && !enemyAttackController.isParrying)
        {
            string path = $"BombHand/{index}";
            return Resources.Load<Sprite>(path);
        }
        else if (!isBombReady && !enemyAttackController.isParrying)
        {
            string path = $"MixHand/{index}";
            return Resources.Load<Sprite>(path);
        }
        else
        {
            return null;
        }

    }

    /// <summary>
    /// мһ…л Ҙл°ӣмқҖ нӮӨк°Җ мғқм„ұлҗң нҷ”мӮҙн‘ңмҷҖ к°ҷмқҖ нӮӨмқём§Җ нҷ•мқён•ңлӢӨ,
    /// </summary>
    /// <returns>мғқм„ұлҗң нҷ”мӮҙн‘ңмҷҖ к°ҷмқҖ нӮӨлҘј мһ…л Ҙл°ӣмңјл©ҙ true, лӢӨлҘё нӮӨлҘј мһ…л Ҙл°ӣмңјл©ҙ false</returns>
    public void CheckInput(ArrowKey key)
    {
        if (!isActive) return;
        if (enemyAttackController.isParrying) return;

        ArrowKey expected = sequence[currentKey];
        ArrowKey correctInput = isReverse ? GetOpposite(expected) : expected;

        // нҸӯнғ„мқј кІҪмҡ° нҸӯнғ„ м• лӢҲл©”мқҙм…ҳ мһ¬мғқ
        if (key == correctInput)
        {
            animator.enabled = false; // м• лӢҲл©”мқҙм…ҳ л№„нҷңм„ұнҷ”

            Transform arrowTransform = arrowParent.Find(currentKey.ToString());

            if (arrowTransform != null)
            {
                StartCoroutine(FadeOutAndShrink(arrowTransform.gameObject));
            }

            if (GetMixHandSprite(key.ToString()) != null)
            {
                sr.sprite = GetMixHandSprite(key.ToString());
            }

            currentKey++;
            SoundManager.Instance.PlaySound(0); // мӮ¬мҡҙл“ң мһ¬мғқ

            if (currentKey >= sequence.Count)
                SuccessInput();
        }
    }

    private IEnumerator FadeOutAndShrink(GameObject target)
    {
        float duration = 0.3f;
        float time = 0f;

        Image img = target.transform.Find("Arrow").GetComponent<Image>();
        Vector3 startScale = target.transform.localScale;
        Color startColor = img.color;

        while (time < duration)
        {
            if (target == null || img == null) yield break; // мӨ‘к°„м—җ нҢҢкҙҙлҗҳл©ҙ мў…лЈҢ

            float t = time / duration;
            target.transform.localScale = Vector3.Lerp(startScale, Vector3.zero, t);
            img.color = Color.Lerp(startColor, new Color(startColor.r, startColor.g, startColor.b, 0f), t);
            time += Time.deltaTime;
            yield return null;
        }

        if (target != null)
            target.SetActive(false);
    }




    /// <summary>
    /// мғқм„ұлҗң нҷ”мӮҙн‘ңлҘј мӨ‘м•ҷмқ„ кё°мӨҖмңјлЎң к°„кІ©мқҙ spacingмқҙ лҗҳлҸ„лЎқ л°°м№ҳ
    /// </summary>
    private void ArrangeChildrenCentered()
    {
        List<Transform> activeChildren = new();

        foreach (Transform child in arrowParent)
        {
            if (child.gameObject.activeSelf)
                activeChildren.Add(child);
        }

        int count = activeChildren.Count;
        float startX = -((count - 1) * spacing) / 2f;

        for (int i = 0; i < count; i++)
        {
            activeChildren[i].localPosition = new Vector3(startX + i * spacing, 0f, 0f);
        }
    }


    /// <summary>
    /// нҳ„мһ¬ м§„н–ү мӨ‘мқё нҷ”мӮҙн‘ң мғқм„ұ л°Ҹ мһ…л Ҙ мӢңнҖёмҠӨмқҳ лӘЁл“  нҷ”мӮҙн‘ңлҘј мҲңм„ңлҢҖлЎң мһ…л Ҙн•ҳм—¬, м„ұкіө мІҳлҰ¬
    /// </summary>
    private void SuccessInput()
    {
        animator.enabled = true; // м• лӢҲл©”мқҙм…ҳ нҷңм„ұнҷ”
        int increHp = GameManager.Instance.Combo + 1;
        GameManager.Instance.IncreCombo();

        ClearArrow();
        Debug.Log("м„ұкіө");
        arrowBackground.SetActive(false);
        arrowTimer.gameObject.SetActive(false);
        GameManager.Instance.TakeDamage(-increHp);
        if (isBombReady)
        {
            throwBackGround.SetActive(true);
            animator.SetTrigger("Throw");
            isBombReady = false;
            leftBombCooldown = bombCooldown;
            StartCoroutine(DelayThrow());

        }
        else
        {
            createBread.SetActive(true);
            createBread.GetComponent<Animator>().Play("breadEffect Animation");
        }
        SoundManager.Instance.PlaySound(2); // мӮ¬мҡҙл“ң мһ¬мғқ
        isActive = false;
        StartCoroutine(DelayedStartArrowInput());
    }

    IEnumerator DelayThrow()
    {
        arrowTimer.gameObject.SetActive(false);
        yield return new WaitForSeconds(1f);
        explosiveAnim.Play("enemyhit Animation");
        Stage.Instance.TakeDamage(60);
        explosiveAnim.gameObject.GetComponent<Image>().enabled = true;
        enemySprite.sprite = GetEnemySprite();
        explosiveAnim.enabled = true;
        if (Stage.Instance.GetStageData().enemyHp > 0)
        {
            yield return new WaitForSeconds(1f);
            explosiveAnim.gameObject.GetComponent<Image>().enabled = false;
            explosiveAnim.enabled = false;
            if (!enemyAttackController.isParrying)
            {
                arrowTimer.gameObject.SetActive(true);
            }
            throwBackGround.SetActive(false);
        }
        else
        {
            yield return new WaitForSeconds(1f);
            explosiveAnim.gameObject.GetComponent<Image>().enabled = false;
            explosiveAnim.enabled = false;
            enemyDieEffect.gameObject.GetComponent<Image>().enabled = true;
            enemyDieEffect.enabled = true;
            StopCoroutine(GameManager.Instance.enemyCoro);
            Stage.Instance.StopAllCoroutines();
            StopCoroutine(DelayedStartArrowInput());
            StopInput();
            arrowBackground.SetActive(false);
            yield return new WaitForSeconds(1f);
            enemyDieEffect.gameObject.SetActive(false);
            GameManager.Instance.StageEnd();
            Debug.Log("м Ғ мӮ¬л§қ2");

        }
    }
    public Sprite GetEnemySprite()
    {
        int index = 0;
        if (Stage.Instance.GetStageData().enemyHp <= 0)
        {
            index = 3;
        }
        else if (Stage.Instance.GetStageData().enemyHp <= Mathf.FloorToInt(Stage.Instance.GetStageData().enemyStartHp * 0.5f))
        {
            index = 2;
        }
        else
        {
            index = 1;
        }
        string path = $"EnemySprite/Enemy{GameManager.Instance.nowStage}_{index}";
        Debug.Log(Resources.Load<Sprite>(path).name);
        return Resources.Load<Sprite>(path);
    }

    private IEnumerator DelayedStartArrowInput()
    {
        customer.transform.GetChild(customerIndexList[0]).gameObject.GetComponent<Animator>().enabled = false;
        customer.transform.GetChild(customerIndexList[0]).gameObject.GetComponent<Image>().sprite = Resources.Load<Sprite>($"Customers/Customer{customerIndexList[0]}_3");
        yield return new WaitForSeconds(2f); // н•ң н”„л Ҳмһ„ кё°лӢӨлҰј вҶ’ Destroy л°ҳмҳҒлҗЁ
        customer.transform.GetChild(customerIndexList[0]).gameObject.GetComponent<Animator>().enabled = true;
        customerIndexList.RemoveAt(0);
        customerIndexList.Add(ChangeCustomerSprite());
        createBread.SetActive(false);
        StartArrowInput();
    }

    private void FailInput()
    {
        animator.enabled = true; // м• лӢҲл©”мқҙм…ҳ нҷңм„ұнҷ”
        GameManager.Instance.ResetCombo();
        isActive = false;
        ClearArrow();
        arrowBackground.SetActive(false);
        arrowTimer.gameObject.SetActive(false);
        Debug.Log("мӢӨнҢЁ");
        SoundManager.Instance.PlaySound(3); // мӮ¬мҡҙл“ң мһ¬мғқ
        StartCoroutine(DelayedFailInput());
    }

    public void StopInput()
    {
        isActive = false;
        ClearArrow();
        arrowTimer.gameObject.SetActive(false);
    }

    private IEnumerator DelayedFailInput()
    {
        customer.transform.GetChild(customerIndexList[0]).gameObject.GetComponent<Animator>().enabled = false;
        customer.transform.GetChild(customerIndexList[0]).gameObject.GetComponent<Image>().sprite = Resources.Load<Sprite>($"Customers/Customer{customerIndexList[0]}_4");
        yield return new WaitForSeconds(2f); // н•ң н”„л Ҳмһ„ кё°лӢӨлҰј вҶ’ Destroy л°ҳмҳҒлҗЁ
        customer.transform.GetChild(customerIndexList[0]).gameObject.GetComponent<Animator>().enabled = true;
        customerIndexList.RemoveAt(0);
        customerIndexList.Add(ChangeCustomerSprite());
        StartArrowInput();
    }

    /// <summary>
    /// мғқм„ұлҗң нҷ”мӮҙн‘ңлҘј м „л¶Җ м ңкұ°
    /// </summary>
    public void ClearArrow()
    {
        foreach (Transform child in arrowParent)
            Destroy(child.gameObject);

        sequence.Clear();
    }

    /// <summary>
    /// лӘЁл“  кі к°қл“Өмқҳ мҳӨлёҢм қнҠёлҘј л№„нҷңм„ұнҷ”н•©лӢҲлӢӨ.
    /// </summary>
    private void ClearCustomer()
    {
        for (int i = 0; i < customer.transform.childCount; i++)
        {
            customer.transform.GetChild(i).gameObject.SetActive(false);
            waitingcustomer.transform.GetChild(i).gameObject.SetActive(false);
            waitingCustomer2.transform.GetChild(i).gameObject.SetActive(false);
        }
    }
}
